<?php

namespace Coursora\ProfessoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessoreRepository extends EntityRepository
{
}
